apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: 
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_require_tls: true
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'default-receiver'
    receivers:
    - name: 'default-receiver'
      email_configs:
      - to: ' @ic.ac.uk'
        from: ' @gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: ' @gmail.com'
        auth_identity: ' @gmail.com'
        auth_password: ' '
