apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aki-detection-state
  namespace: 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aki-detection
  namespace:  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aki-detection
  template:
    metadata:
      labels:
        app: aki-detection
    spec:
      containers:
      - name: aki-detection
        image: 
        command: ["/model/app.py"]
        args:
        - "--history=/hospital-history/history.csv"
        env:
        - name: MLLP_ADDRESS
          value:  coursework6:8440
        - name: PAGER_ADDRESS
          value:  coursework6:8441
        - name: PYTHONUNBUFFERED
          value: "1"
        ports:
        - name: http
          containerPort: 8000
        volumeMounts:
          - mountPath: "/hospital-history"
            name: hospital-history
            readOnly: true
          - mountPath: "/state"  # Add this volume mount for the /state directory
            name: aki-detection-state
            readOnly: false
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"  # Reduced CPU limit
          requests:
            memory: "100Mi"
            cpu: "100m"  # Reduced CPU request
      initContainers:
      - name: copy-hospital-history
        image:  
        volumeMounts:
          - mountPath: "/hospital-history"
            name: hospital-history
          - mountPath: "/state"
            name: aki-detection-state
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"  # Reduced CPU limit
          requests:
            memory: "100Mi"
            cpu: "100m"  # Reduced CPU request
      volumes:
      - name: hospital-history
        emptyDir:
          sizeLimit: 50Mi
      - name: aki-detection-state
        persistentVolumeClaim:
          claimName: aki-detection-state